services:
  apigateway.host:
    image: ${DOCKER_REGISTRY-}apigatewayhost
    build:
      context: .
      dockerfile: src/ApiGateway.Host/Dockerfile
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - redis
      - wiremock
    networks:
      - gateway-net

  redis:
    image: redis:7-alpine
    ports:
      - "6381:6379"
    networks:
      - gateway-net

  wiremock:
    image: wiremock/wiremock:3.3.1
    ports:
      - "8081:8080" # lembrar que a porta da esquerda a minha! a q eu vou digitar no postan. eu sempre confundo
    volumes: # nesse caso, o volume nao eh usado para persistencia. 
         #isso auqi ta me falando que o caminho de pasta na esquerda do : vai aparecer como o lado direito dentro do contaiber
      - ./infra/wiremock/mappings:/home/wiremock/mappings
    command: ["--verbose"] #sobreescrevendo o comando padrao e usano o verbose pra escrever no terminal cada request
    networks:
      - gateway-net

  #eu tava tendo um problma com o keycloak que toda vez que eu fechava o vs e voltava, todas as configuracoes (client, role, user) eram
  #apagadas e eu tinha que configurasr tudo dnv. isso eh pq eu nao tinha congigurado um volume nele
  keycloak:
    image: quay.io/keycloak/keycloak:23.0
    ports:
      - "8080:8080"
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    command: ["start-dev"]
    networks: 
      - gateway-net
    volumes: #aqui
      - keycloak_data:/opt/keycloak/data 

networks:
  gateway-net: # por padrao cada ocntainer eh isolado. o bridge cria tipo uma rede virtual privaada onde todos os containers que estaoo nela consigam se comunicar
    driver: bridge
    #por isso eu escrevo "http://wiremock:8080" e nao "http://localhost:8080"

volumes:
  keycloak_data: #aqui, eu to criando um volume sem nada depois pois eu to deixando o proprio docker criar e gerenciar esse volume

